/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts,scss}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#451de3',
        'primary-container': '#5e43fb',
        'on-primary': '#ffffff',
        'on-primary-container': '#e7e2ff',
        'inverse-primary': '#c6bfff',
        'primary-fixed': '#e4dfff',
        'primary-fixed-dim': '#c6bfff',
        secondary: '#006688',
        'secondary-container': '#00c1fd',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#004b65',
        'secondary-fixed': '#c2e8ff',
        'secondary-fixed-dim': '#75d1ff',
        background: '#f9f9fc',
        'on-background': '#1a1c1e',
        surface: '#f9f9fc',
        'surface-dim': '#dadadc',
        'surface-bright': '#f9f9fc',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f3f6',
        'surface-container': '#eeeef0',
        'surface-container-high': '#e8e8ea',
        'surface-container-highest': '#e2e2e5',
        'on-surface': '#1a1c1e',
        'on-surface-variant': '#474556',
        'inverse-surface': '#2f3133',
        'inverse-on-surface': '#f0f0f3',
        outline: '#787588',
        'outline-variant': '#c8c4d9',
        'surface-tint': '#5638f3',
        tertiary: '#4b4f52',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#63676a',
        'on-tertiary-container': '#e3e6e9',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        manrope: ['Manrope', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
      },
      fontSize: {
        h1: ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        h2: ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6' }],
        'body-md': ['16px', { lineHeight: '1.6' }],
        'label-sm': ['12px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        unit: '4px',
        'margin-page': '24px',
        gutter: '16px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
      },
      boxShadow: {
        card: '0px 8px 24px rgba(94,67,251,0.04)',
        'card-hover': '0px 12px 32px rgba(94,67,251,0.08)',
        'card-active': '0px 16px 40px rgba(94,67,251,0.12)',
      },
    },
  },
  plugins: [],
};
